# #####################################################################
# Automatically generated by qmake (2.01a) Sat Nov 21 14:21:41 2009
# #####################################################################
TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += btkeyboard.h
SOURCES += btkeyboard.cpp \
    main.cpp

CONFIG += link_pkgconfig
PKGCONFIG += glib-2.0
